[book]
title = "The Art of Asking WHY?"
authors = ["Miguel Velez"]
language = "es"
src = "."

[build]
build-dir = "../../book/es"

[output.html]
default-theme = "navy"

[output.html.print]
enable = true
